# Generated by Django 5.1.4 on 2025-02-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Autor del blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Autor del blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Contenido del blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Contenido del blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo del blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo del blog'),
        ),
    ]
