# Generated by Django 5.1.4 on 2025-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='courses/uploads/', verbose_name='Temario'),
        ),
    ]
