# Generated by Django 5.1.4 on 2025-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Imagen del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Temario'),
        ),
    ]
