# Generated by Django 5.1.4 on 2025-02-09 12:52

import ckeditor.fields
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Imagen del curso'),
        ),
    ]
