# Generated by Django 5.1.4 on 2025-02-16 17:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_content_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='call_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de llamada'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido del curso'),
        ),
    ]
